### ISSUE TITLE
 throw new TypeError(ErrorCodes.ClientMissingIntents);

### ISSUE THREAD

**Issue by ghost** [I2rys/APGDB#1]
$ node index.js

Output: 

/home/node_modules/discord.js/src/client/Client.js:480
      throw new TypeError(ErrorCodes.ClientMissingIntents);
      ^

TypeError [ClientMissingIntents]: Valid intents must be provided for the Client.
    at Client._validateOptions (/home/node_modules/discord.js/src/client/Client.js:480:13)
    at new Client (/home/node_modules/discord.js/src/client/Client.js:78:10)
    at Object.<anonymous> (/home/pi/APGDB/index.js:7:13)
    at Module._compile (node:internal/modules/cjs/loader:1149:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1203:10)
    at Module.load (node:internal/modules/cjs/loader:1027:32)
    at Module._load (node:internal/modules/cjs/loader:868:12)
    at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
    at node:internal/main/run_main_module:23:47 {
  code: 'ClientMissingIntents'
}

Node.js v18.10.0

whats wrong?

**Comment by I2rys** [comment]
Hello @Aqtic0l, Most of my repositories used the old version of Discord which is v12 so to fix this problem you just have to downgrade your discord.js to v12
```
npm uninstall discord.js && npm i discord.js@12.5.3
```

I hope this fixes your problem.

**Comment by ghost** [comment]
Thx its Works!!
